# Build and autotest script for PX4 Firmware
# http://travis-ci.org

language: cpp

matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: required
      env: GCC_VER=4.8
      services:
        - docker
    #- os: linux
    #  sudo: required
    #  env: GCC_VER=4.9
    #  services:
    #    - docker
    - os: osx
      osx_image: xcode7
      sudo: true

cache:
  directories:
    - $HOME/.ccache

before_install:
  - cd ${TRAVIS_BUILD_DIR} && git fetch --unshallow && git fetch --all --tags
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         docker pull px4io/px4-dev-base;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
         brew tap PX4/homebrew-px4
      && brew update; brew update
      && brew install cmake ninja
      && brew install genromfs
      && sudo easy_install pip
      && sudo pip install empy
      ;
    fi

env:
  global:
# AWS KEY: $PX4_AWS_KEY
    - secure: "XknnZHWBbpHbN4f3fuAVwUztdLIu8ej4keC3aQSDofo3uw8AFEzojfsQsN9u77ShWSIV4iYJWh9C9ALkCx7TocJ+xYjiboo10YhM9lH/8u+EXjYWG6GHS8ua0wkir+cViSxoLNaMtmcb/rPTicJecAGANxLsIHyBAgTL3fkbLSA="
# AWS SECRET: $PX4_AWS_SECRET
    - secure: "h6oajlW68dWIr+wZhO58Dv6e68dZHrBLVA6lPXZmheFQBW6Xam1HuLGA0LOW6cL9TnrAsOZ8g4goB58eMQnMEijFZKi3mhRwZhd/Xjq/ZGJOWBUrLoQHZUw2dQk5ja5vmUlKEoQnFZjDuMjx8KfX5ZMNy8A3yssWZtJYHD8c+bk="
    - PX4_AWS_BUCKET=px4-travis

script:
  - git submodule update --quiet --init --recursive
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      docker run --rm -v `pwd`:`pwd`:rw -v $HOME/.ccache:$HOME/.ccache:rw -e CCACHE_DIR=$HOME/.ccache -w=`pwd` --user=$UID -it px4io/px4-dev-base /bin/bash -c "make check VECTORCONTROL=1";
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      make check_posix_sitl_default;
    fi

after_success:
  - make package_firmware && mkdir s3deploy-archive && mv Firmware.zip s3deploy-archive
  - find . -type f -name 'nuttx-*-default.px4' -exec cp "{}" . \;
  - find . -maxdepth 1 -mindepth 1 -type f -name 'nuttx-*-default.px4' | sed 's/.\/nuttx-//' | sed 's/-default.px4//' | xargs -I{} mv nuttx-{}-default.px4 {}_default.px4
  - mkdir s3deploy-branch && mv *_default.px4 build_px4fmu-v2_default/parameters.xml build_px4fmu-v2_default/airframes.xml s3deploy-branch

deploy:
  - provider: s3
    access_key_id: $PX4_AWS_KEY
    secret_access_key:
      secure: $PX4_AWS_SECRET
    bucket: px4-travis
    local_dir: s3deploy-archive
    upload-dir: archives/Firmware/$TRAVIS_BRANCH/$TRAVIS_BUILD_ID
    acl: public_read
    skip_cleanup: true
    on:
      branch: master
      branch: beta
      branch: stable
      branch: docker
      condition: $GCC_VER = 4.8
  - provider: s3
    access_key_id: $PX4_AWS_KEY
    secret_access_key:
      secure: $PX4_AWS_SECRET
    bucket: px4-travis
    local_dir: s3deploy-branch
    upload-dir: Firmware/$TRAVIS_BRANCH
    acl: public_read
    skip_cleanup: true
    on:
      branch: master
      branch: beta
      branch: stable
      branch: docker
      condition: $GCC_VER = 4.8
  - provider: releases
    api_key: 
      secure: cdHWLRBxA5UlYpOS0Sp891QK7PFmMgQ5ZWs1aPt+sw0rIrowyWMHCwXNBEdUqaExHYNYgXCUDI0EzNgfB7ZcR63Qv1MQeoyamV4jsxlyAqDqmxNtWO82S6RhHGeMLk26VgFKzynVcEk1IYlQP2nqzMQLdu+jTrngERuAIrCdRuc=
    file: "Firmware.zip"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      repo: PX4/Firmware
      condition: $GCC_VER = 4.8

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2b9c4a4cb2211f8befba
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
  slack:
    secure: "QKw73Zel/s3JAbe/7XyO9tPnJwiiGFpYzSjdR8lG3tYFjRdXZnhxG4c+G7bkgkaPTS4Hult33VXE3kcEqOI7+C+eRwRlZhDfL0knQbXVCxjcLjzmUFdoPOwurlgZDw66PFWCi5tZcLKSRo3u4U8ibT4WKi3jm9sDSyOcfBAucMU="
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
