language: cpp

git:
  depth: 100
  submodules: false

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: xenial
      # In order to stay under the coverity rate limit, we only run this weekly
      # and not on push which is configured in travis-ci settings.
      if: branch = master

before_install:
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install:
    - export PATH=$HOME/.local/bin:$PATH
    - pip install --user --upgrade pip
    - pip install --user -r Tools/setup/requirements.txt

script:
    - make

addons:
  coverity_scan:
    project:
      name: "PX4/Firmware"
      description: "Build submitted via Travis CI"
    notification_email: ci@px4.io
    build_command_prepend: "make distclean"
    build_command: "make px4_sitl_default"
    branch_pattern: coverity_scan
