name: Build Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-base-bionic:2019-10-24
    steps:
    - uses: actions/checkout@v1
    - name: check_format
      env:
        CI: true
      run: make check_format
    - name: main tests
      run: make tests
