name: Build & Publish Docker images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - '*'

jobs:
  docker-jammy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build if changed
      run: |
        COMMITS=${{ github.event.pull_request.commits }}
        if [[ -n "$COMMITS" ]]; then
          # Prepare enough depth for diffs with main
          git fetch --depth="$(( commits + 1 ))"
        fi
        if ! git diff --exit-code origin/main -- Tools/setup/ubuntu.sh Tools/setup/Dockerfile-jammy; then
          (cd Tools/setup && docker build . -t px4-dev -f Dockerfile-jammy --build-arg git_ref=${{ github.sha }})
          export SRC_DIR="/PX4-Autopilot"
          git config --global --add safe.directory ${SRC_DIR}
          export LOCAL_USER_ID=${UID}
          docker run --rm -w "${SRC_DIR}" --user="$(id --user):$(id --group)" --volume=$(pwd):${SRC_DIR}:rw px4-dev make px4_fmu-v2
        fi
