name: Deploy metadata for all targets

on:
  push:
    branches:
    - 'main'
    - 'release/*'
    - 'pr-metadata-test'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    needs: enumerate_targets
    container: px4io/px4-dev-nuttx-focal:2021-09-08
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{secrets.ACCESS_TOKEN}}

    - name: make ${{matrix.target}}
      run: make ${{matrix.target}}

    - name: parameter & events metadata
      run: |
        make ${{matrix.target}} ver_gen events_json actuators_json
        ./src/lib/version/get_git_tag_or_branch_version.sh build/px4_fmu-v5_default >> $GITHUB_ENV
        cd build/px4_fmu-v5_default
        mkdir _metadata || true
        cp parameters.* events/*.xz actuators.json* _metadata

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        AWS_S3_BUCKET: 'px4-travis'
        AWS_ACCESS_KEY_ID: ASDFJJGS + DFS ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ASDF ASDF + ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-1'
        SOURCE_DIR: 'build/px4_fmu-v5_default/_metadata/'
        DEST_DIR: 'Firmware/${{ env.version }}/px4_fmu-v5_default/'

    - name: Check environment variables
      run: echo $GITHUB_ENV && echo "\n\n" && echo "${{env}}" && echo "\n\n" && env

