name: Docs Metadata Checks

permissions:
  contents: write

on:
  pull_request: {}
  push:
    branches:
      - main
      - 'release/**'

jobs:
  metadata-check:
    name: ${{ matrix.name }} metadata
    runs-on: [runs-on,runner=2cpu-linux-x64,image=ubuntu24-full-x64,"run-id=${{ github.run_id }}",spot=true]
    container:
      image: ghcr.io/px4/px4-dev:v1.16.0-rc1
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: uORB Graphs
            script: Tools/ci/metadata_uorb_graph.sh
          - name: Failsafe Web
            script: Tools/ci/metadata_failsafe_web.sh
          - name: uORB Messages
            script: Tools/ci/metadata_msg_docs.sh
          - name: Parameter Reference
            script: Tools/ci/metadata_parameters.sh
          - name: Airframe Reference
            script: Tools/ci/metadata_airframe.sh
          - name: Module Reference
            script: Tools/ci/metadata_modules.sh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Mark all directories safe for Git
        run: git config --system --add safe.directory '*'

      - name: Run ${{ matrix.name }} metadata check
        run: ${{ matrix.script }} --test-only
