name: FMU-v5 clang-tidy

on:
  push:
    branches:
    - 'master'
    - 'fmu-v5-actions'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/render-se/px4-clang:latest
      credentials:
        token: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{secrets.ACCESS_TOKEN}}

    - name: make clang-tidy_px4_fmu-v5
      run: make clang-tidy_px4_fmu-v5
