name: FMU-v5 lcov

on:
  push:
    branches:
    - 'master'
    - 'fmu-v5-actions'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/render-se/px4-nuttx:latest
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{secrets.ACCESS_TOKEN}}
    - name: Run lcov
      run: make coverage_px4_fmu-v5
