name: Fuzzing
on:
  schedule:
    - cron: '0 6 * * *'  # UTC 6am every day.

permissions:
  contents: read
  issues: write # for JasonEtco/create-an-issue

env:
  RUNS_IN_DOCKER: true

jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    container:
      image: px4io/px4-dev:v1.16.0-rc2-4-gb67c65bfe6
    steps:
      - name: Install Dependencies
        run: |
          apt update && apt install -y clang

      - name: Fix git in Container
        run: |
          git config --global --add safe.directory $(realpath .)

      - uses: actions/checkout@v4

      - name: Build and Run Fuzz Tests
        run: |
          # Only build the tests
          export CC=clang
          export CXX=clang++
          make tests TESTFILTER=__no_tests__

          # Run the fuzz tests
          for fuzz_binary in build/px4_sitl_test/*fuzz*; do
            ./Tools/ci/run_fuzz_tests.sh $fuzz_binary 15m
          done

      # Create a github issue in case of a failure
      - name: Create Issue
        if: ${{ failure() }}
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          filename: .github/fuzzing_issue_template.md
