name: tiiuea-pixhawk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pixhawk:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout px4-firmware
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          path: px4-firmware
          submodules: recursive
          fetch-depth: 0

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      # Run docker build
      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts/px4/pixhawk
          ./package.sh ../../../px4-firmware ../../../bin
          popd

      - name: Install jfrog CLI tool
        env:
          JFROG_CLI_URL: https://ssrc.jfrog.io/artifactory/ssrc-gen-public-remote-cache/tools/jfrog/jfrog-1.45.2.tar.gz
        if: github.event_name == 'push'
        run: |
          set -exu
          mkdir -p "$GITHUB_WORKSPACE/.jfrog/bin"
          curl -L "$JFROG_CLI_URL" -o "$GITHUB_WORKSPACE/.jfrog/jfrog.tar.gz"
          tar -C "$GITHUB_WORKSPACE/.jfrog/bin" -zxf "$GITHUB_WORKSPACE/.jfrog/jfrog.tar.gz"
          echo "$GITHUB_WORKSPACE/.jfrog/bin" >> "$GITHUB_PATH"
          echo "JFROG_CLI_HOME_DIR=$GITHUB_WORKSPACE/.jfrog" >> "$GITHUB_ENV"

      - name: Import Artifactory token
        env:
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          CI: true
        if: github.event_name == 'push'
        run: |
          set -exu
          jfrog rt c import "$ARTIFACTORY_TOKEN"
          jfrog rt ping

      - name: Upload px4-firmware build to Artifactory
        env:
          ARTIFACTORY_GEN_REPO: gen-public-local
          BUILD_NAME_PX4: px4-firmware
          CI: true
        if: github.event_name == 'push'
        run: |
          set -exu
          pkg=$(find bin -name 'px4_fmu-v5_ssrc*.px4')
          saluki_pkg=$(find bin -name 'ssrc_saluki-*.px4')
          pkg_name=$(basename $pkg)
          saluki_pkg_name=$(basename $saluki_pkg)
          jfrog rt u --target-props COMMIT="$GITHUB_SHA" \
                     --build-name "$BUILD_NAME_PX4" \
                     --build-number "$GITHUB_SHA" \
                     "$pkg" \
                     "$ARTIFACTORY_GEN_REPO/builds/px4-firmware/pixhawk/$pkg_name"
          jfrog rt u --target-props COMMIT="$GITHUB_SHA" \
                     --build-name "$BUILD_NAME_PX4" \
                     --build-number "$GITHUB_SHA" \
                     "$saluki_pkg" \
                     "$ARTIFACTORY_GEN_REPO/builds/px4-firmware/saluki/$saluki_pkg_name"
          jfrog rt build-publish "$BUILD_NAME_PX4" "$GITHUB_SHA"
          jfrog rt bpr "$BUILD_NAME_PX4" "$GITHUB_SHA" "$ARTIFACTORY_GEN_REPO" \
                       --status dev \
                       --comment "development build"
          jfrog rt cp --flat \
                      "$ARTIFACTORY_GEN_REPO/builds/px4-firmware/pixhawk/$pkg_name" \
                      "$ARTIFACTORY_GEN_REPO/builds/px4-firmware/pixhawk/latest/px4_fmu-v5_ssrc-LATEST.px4"
          jfrog rt cp --flat \
                      "$ARTIFACTORY_GEN_REPO/builds/px4-firmware/saluki/$saluki_pkg_name" \
                      "$ARTIFACTORY_GEN_REPO/builds/px4-firmware/saluki/latest/ssrc_saluki-v1_default.px4"

      - name: Upload px4-fwupdater build to Artifactory
        env:
          ARTIFACTORY_DEB_REPO: debian-public-local
          DISTRIBUTION: focal
          COMPONENT: fog-sw
          ARCHITECTURE: amd64
          BUILD_NAME_DEB: px4-fwupdater
          CI: true
        if: github.event_name == 'push'
        run: |
          set -exu
          pkg=$(find bin -name 'px4fwupdater*.deb')
          jfrog rt u --deb "$DISTRIBUTION/$COMPONENT/$ARCHITECTURE" \
                     --target-props COMMIT="$GITHUB_SHA" \
                     --build-name "$BUILD_NAME_DEB" \
                     --build-number "$GITHUB_SHA" \
                     "$pkg" \
                     "$ARTIFACTORY_DEB_REPO"
          jfrog rt build-publish "$BUILD_NAME_DEB" "$GITHUB_SHA"
          jfrog rt bpr "$BUILD_NAME_DEB" "$GITHUB_SHA" "$ARTIFACTORY_DEB_REPO" \
                       --status dev \
                       --comment "development build"
