name: tii-px4-sitl

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tii-px4-sitl:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:

      - name: Checkout px4-firmware
        uses: actions/checkout@v3
        with:
          path: px4-firmware
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      # Run docker build
      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          cd px4-firmware
          ./clone_public.sh
          ./build_sitl.sh ../bin/
          ls ../bin/

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/tiiuae/tii-px4-sitl
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha
            type=raw,value=latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tii-px4-sitl image and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./px4-firmware/packaging/Dockerfile.sitl
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: jfrog/setup-jfrog-cli@v3
        if: github.event_name == 'push'
        env:
          JF_ENV_1: ${{ secrets.ARTIFACTORY_CLOUD_TOKEN }}

      - name: Upload to Artifactory (px4-sitl)
        env:
          ARTIFACTORY_GEN_REPO: gen-public-local
          BUILD_NAME: px4-sitl
          CI: true
        if: github.event_name == 'push'
        run: |
          set -exu
          jfrog rt ping
          pkg=$(find bin -name 'px4_sitl_build*.tar.gz')
          pkg_name=$(basename $pkg)
          jfrog rt u --target-props COMMIT="$GITHUB_SHA" \
                     --build-name "$BUILD_NAME" \
                     --build-number "$GITHUB_SHA" \
                     "$pkg" \
                     "$ARTIFACTORY_GEN_REPO/builds/px4-firmware/sitl/$pkg_name"
          jfrog rt build-publish "$BUILD_NAME" "$GITHUB_SHA"
          jfrog rt bpr "$BUILD_NAME" "$GITHUB_SHA" "$ARTIFACTORY_GEN_REPO" \
                       --status dev \
                       --comment "development build"
          jfrog rt cp --flat \
                      "$ARTIFACTORY_GEN_REPO/builds/px4-firmware/sitl/$pkg_name" \
                      "$ARTIFACTORY_GEN_REPO/builds/px4-firmware/sitl/latest/px4_sitl_build.tar.gz"

      - name: Upload to Artifactory (px4-gazebo-data)
        env:
          ARTIFACTORY_GEN_REPO: gen-public-local
          BUILD_NAME: gazebo-data
          CI: true
        if: github.event_name == 'push'
        run: |
          set -exu
          jfrog rt ping
          pkg=$(find bin -name 'px4_gazebo_data*.tar.gz')
          pkg_name=$(basename $pkg)
          jfrog rt u --target-props COMMIT="$GITHUB_SHA" \
                     --build-name "$BUILD_NAME" \
                     --build-number "$GITHUB_SHA" \
                     "$pkg" \
                     "$ARTIFACTORY_GEN_REPO/builds/gazebo-data/$pkg_name"
          jfrog rt build-publish "$BUILD_NAME" "$GITHUB_SHA"
          jfrog rt bpr "$BUILD_NAME" "$GITHUB_SHA" "$ARTIFACTORY_GEN_REPO" \
                       --status dev \
                       --comment "development build"
          jfrog rt cp --flat \
                      "$ARTIFACTORY_GEN_REPO/builds/gazebo-data/$pkg_name" \
                      "$ARTIFACTORY_GEN_REPO/builds/gazebo-data/latest/px4_gazebo_data.tar.gz"
