name: tii-px4-sitl-gzsim

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
  packages: write

jobs:
  tii-px4-sitl-gzsim:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout px4-firmware
        uses: actions/checkout@v4
        with:
          path: px4-firmware
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Prepare px4-firmware
        run: |
          set -eux
          cd px4-firmware
          ./clone_public.sh

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/tiiuae/tii-px4-sitl-gzsim
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha
            type=raw,value=latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tii-px4-sitl-gzsim image and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./px4-firmware/packaging/Dockerfile.sitl_gzsim
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
