name: tii-px4-sitl

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tii-px4-sitl:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:

      - name: Checkout px4-firmware
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_REPO_TOKEN }}
          path: px4-firmware
          submodules: recursive
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      # Run docker build
      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd px4-firmware
          IMAGE_NAME=localhost:5000/tiiuae/px4-sitl-artifacts:latest ./build_sitl.sh ../bin/
          popd
          docker push localhost:5000/tiiuae/px4-sitl-artifacts:latest

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/tiiuae/tii-px4-sitl
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha
            type=raw,value=latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tii-px4-sitl image and push
        uses: docker/build-push-action@v2
        with:
          context: px4-firmware/
          file: ./px4-firmware/packaging/Dockerfile.docker
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            FROM_ARTIFACTS=localhost:5000/tiiuae/px4-sitl-artifacts:latest

      - name: Install jfrog CLI tool
        env:
          JFROG_CLI_URL: https://ssrc.jfrog.io/artifactory/ssrc-gen-public-remote-cache/tools/jfrog/jfrog-1.45.2.tar.gz
        if: github.event_name == 'push'
        run: |
          set -exu
          mkdir -p "$GITHUB_WORKSPACE/.jfrog/bin"
          curl -L "$JFROG_CLI_URL" -o "$GITHUB_WORKSPACE/.jfrog/jfrog.tar.gz"
          tar -C "$GITHUB_WORKSPACE/.jfrog/bin" -zxf "$GITHUB_WORKSPACE/.jfrog/jfrog.tar.gz"
          echo "$GITHUB_WORKSPACE/.jfrog/bin" >> "$GITHUB_PATH"
          echo "JFROG_CLI_HOME_DIR=$GITHUB_WORKSPACE/.jfrog" >> "$GITHUB_ENV"

      - name: Upload to Artifactory (px4-sitl)
        env:
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          ARTIFACTORY_GEN_REPO: gen-public-local
          BUILD_NAME: px4-sitl
          CI: true
        if: github.event_name == 'push'
        run: |
          set -exu
          jfrog rt c import "$ARTIFACTORY_TOKEN"
          jfrog rt ping
          pkg=$(find bin -name 'px4_sitl_build*.tar.gz')
          pkg_name=$(basename $pkg)
          jfrog rt u --target-props COMMIT="$GITHUB_SHA" \
                     --build-name "$BUILD_NAME" \
                     --build-number "$GITHUB_SHA" \
                     "$pkg" \
                     "$ARTIFACTORY_GEN_REPO/builds/px4-firmware/sitl/$pkg_name"
          jfrog rt build-publish "$BUILD_NAME" "$GITHUB_SHA"
          jfrog rt bpr "$BUILD_NAME" "$GITHUB_SHA" "$ARTIFACTORY_GEN_REPO" \
                       --status dev \
                       --comment "development build"
          jfrog rt cp --flat \
                      "$ARTIFACTORY_GEN_REPO/builds/px4-firmware/sitl/$pkg_name" \
                      "$ARTIFACTORY_GEN_REPO/builds/px4-firmware/sitl/latest/px4_sitl_build.tar.gz"

      - name: Upload to Artifactory (px4-gazebo-data)
        env:
          ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
          ARTIFACTORY_GEN_REPO: gen-public-local
          BUILD_NAME: gazebo-data
          CI: true
        if: github.event_name == 'push'
        run: |
          set -exu
          jfrog rt c import "$ARTIFACTORY_TOKEN"
          jfrog rt ping
          pkg=$(find bin -name 'px4_gazebo_data*.tar.gz')
          pkg_name=$(basename $pkg)
          jfrog rt u --target-props COMMIT="$GITHUB_SHA" \
                     --build-name "$BUILD_NAME" \
                     --build-number "$GITHUB_SHA" \
                     "$pkg" \
                     "$ARTIFACTORY_GEN_REPO/builds/gazebo-data/$pkg_name"
          jfrog rt build-publish "$BUILD_NAME" "$GITHUB_SHA"
          jfrog rt bpr "$BUILD_NAME" "$GITHUB_SHA" "$ARTIFACTORY_GEN_REPO" \
                       --status dev \
                       --comment "development build"
          jfrog rt cp --flat \
                      "$ARTIFACTORY_GEN_REPO/builds/gazebo-data/$pkg_name" \
                      "$ARTIFACTORY_GEN_REPO/builds/gazebo-data/latest/px4_gazebo_data.tar.gz"
